### ISSUE TITLE
FR: Add alias support

### ISSUE THREAD

**Issue by khalwat** [aelvan/Inlin-Craft#10]
It's be nice instead of using `$_SERVER['DOCUMENT_ROOT']` it'd be nice if it defaulted to `@webroot` -- and it'd also be nice if aliases could be used in the config setting `inlinPublicRoot`

**Comment by aelvan** [comment]
Right, I'll fix. Aliases wasn't a thing when I ported it. ;)

**Comment by adrienne** [comment]
Any luck on this, @aelvan ?

**Comment by aelvan** [comment]
This was added in 2.1.0.
