### ISSUE TITLE
returning array in inline.php didn't work

### ISSUE THREAD

**Issue by frontedbe** [aelvan/Inlin-Craft#11]
The example you provided to put in the config/inline.php file didn't work for me cause I figured you had to return it as an array? It error'ed in "Call to a member function setAttributes() on null"

So I declared it as a variable and then it worked out fine :) Is there something I missed or do you need to update the readme file with a variable declaration of $publicRoot instead of 'publicRoot' => 'xxx'?

**Comment by aelvan** [comment]
Maybe the example isn't clear enough, the inlin.php file should be set up exactly as all other config files in craft, so you need to return an array with the config value, or a multi-env formatted array. Ie, the whole file should be:

```
<?php

return [
    'publicRoot' => 'xxx',
];
```
 
Or:

```
<?php

return [
    '*' => [
       'publicRoot' => 'xxx',
   ],
    'whatever' => [
       'publicRoot' => 'xxx',
   ],
    'prod' => [
       'publicRoot' => 'xxx',
   ],
];
```

Was that what tripped you up?

**Comment by frontedbe** [comment]
Oh my, I did exactly like your first example but also had another Inline plugin installed and running simultaneously :) which was responsible for the error on the config file, my bad! Works as expected now :) thank you!

**Comment by frontedbe** [comment]
There's a typo in your readme file, you mention inlinE.php, which didn't work after all. I changed it to inlin.php and now my environmentvariables finally work like they should :)
[view screenshot](https://cl.ly/spSl)

*EDIT*
Nope, this is not working as expected.

I have a defined ENVIRONMENT in my .env file as 'test'
When I add 'test' with the same publicRoot value to the array of inlin.php, it doesn't load my SVGs
When I add the same publicRoot value to '*', it works...
[view screenshot](https://cl.ly/sq7h)
Losing my mind over this simple issue over here :)
