### ISSUE TITLE
Documentation update required

### ISSUE THREAD

**Issue by BigglesZX** [aelvan/Inlin-Craft#14]
Hi – thanks for your work on this plugin.

I think the documented usage in the README needs to be updated match the plugin behaviour. The example script usage given:

```twig
<script src="{{ craft.inlin.er('/build/svg/my.svg') | raw }}"></script>
```

... should actually read as follows:

```twig
<script>{{ craft.inlin.er('/build/js/script.js') | raw }}</script>
```

... since the plugin will just dump the contents of that file right there, it should be placed between the `script` tags and not inside the `src` attribute.

Thanks again.

**Comment by aelvan** [comment]
Hah, you're right. Congratulations, you're the first to notice in four years. ;) Originally I probably just copied the readme from my [Stamp plugin](https://github.com/aelvan/Stamp-Craft), and didn't update it properly. :)

I've updated with better/correct examples.

**Comment by BigglesZX** [comment]
Perfect – thanks!
