### ISSUE TITLE
Inlin not showing up on the plugins page

### ISSUE THREAD

**Issue by calebbrewer** [aelvan/Inlin-Craft#2]
In my local dev environment the plugin shows up and works. But when I move it to my server it doesn't even show up, but other plugins do.

Any ideas?

Thanks for the great plugin by the way.

**Comment by aelvan** [comment]
Check the case of the folder name, and the plugin files. The plugin folder should be named "inlin" with all lowercase letters. And the main plugin file should be InlinPlugin.php. Using the wrong casing would work on for instance osx, but when moving things to a linux server, it'd break.

If that is correct, check the permissions on the folder, that might also result in this error.

Happy to hear that you find the plugin useful! :)

**Comment by calebbrewer** [comment]
Thanks for the response.
What permissions need to be set on that folder?

**Comment by calebbrewer** [comment]
WOOHOO. It was a case problem. I was sure I had checked that. Thank you!

**Comment by aelvan** [comment]
Great that you got it sorted out! :)
