### ISSUE TITLE
file_exists($filePath) returns false

### ISSUE THREAD

**Issue by sgtpenguin** [aelvan/Inlin-Craft#4]
My example $filePath ends up being 'http://localhost:8888/carbon/public/re/icons/money.svg', 'http://localhost:8888/carbon/public/' coming from 'inlinPublicRoot' and the rest being passed by $fileName.  Checking file_exists($fileName) does work.

`if ($fileName !== '' && file_exists($fileName)) {`

I don't think `file_exists()` should be getting a full url.  From the docs:

> file_exists — Checks whether a file or directory exists

Thanks for writing the plugin!  Let me know what you think.

**Comment by aelvan** [comment]
Right, `inlinPublicRoot` needs to be the file path to your public directory, not the URL. As in the example in the docs:

`'inlinPublicRoot' => '/path/to/website/public/',`

**Comment by sgtpenguin** [comment]
Ah.  I feel silly.  I wasn't using the full file path, but the one relative to my local server.  All good now.  Thank you for the response.
