### ISSUE TITLE
Error property inlin

### ISSUE THREAD

**Issue by kaspar-allenbach** [aelvan/Inlin-Craft#6]
I run craft on an ngnix server.

When using inlin I get this error:

```Neither the property "inlin" nor one of the methods "inlin()", "getinlin()"/"isinlin()" or "__call()" exist and have public access in class "Craft\CraftVariable```

I aded the public path via ```'inlinPublicRoot' => 'path',``` but this doesn't help. Is this a ngnx issue? Or what coul be the problem?

**Comment by aelvan** [comment]
That error message indicates that it can't find the plugin. Is it installed? If so, could it be that the plugin folder is wrongly named, it should be `inline` with all lowercase.

**Comment by kaspar-allenbach** [comment]
That was the error. The folder was named Uppercase. I thought it should be exactly like the containing `.php` file. However: Problem Solved!
