### ISSUE TITLE
Adding assets url from backend, not from template

### ISSUE THREAD

**Issue by jannisborgers** [aelvan/Inlin-Craft#8]
I’m wondering if this is possible. I have a teaser block and when SVGs are added instead of bitmap images, I want them to be inlined instead of output as an image element. Inlin only offers an output tag. Is there a way to insert a field as an argument, or is that not possible with Twig?

**Comment by aelvan** [comment]
That should not be a problem, I think maybe you're overthinking it. You just need to pass the path or url to the craft.inlin.er template variable somehow. How you'd go about this is largely dependant on your usecase, but the gist of it would be something like:

```
{% for myImage in myImages %}
	{% if myImage.extension=='svg' %}
		{{ craft.inlin.er(myImage.url) | raw }}
	{% else %}
		{# Bitmap, do transform #}
	{% endif %}
{% endfor %}
```

Using `.url` requires the asset source url to actually be an url (not just a relative path). If it's not, you could probably construct the path to the image with `myImage.source.path ~ myImage.path` or something.

**Comment by jannisborgers** [comment]
Okay wow, I was not aware that twig functions can take variables as arguments. Sorry to bother you and thanks for the ultra-quick reply!
